[project]
name            = 'nya-lisp'
dynamic         = ['version']
description     = 'A customizable lisp-like execution/templating engine, inspired by RoboTop (robotop.xyz) which was made by Colon (gdcolon.com) r!execute'
readme          = "README.md"
requires-python = ">=3.12"
dependencies    = []

# [project.scripts]
# nya_lisp = "nya_lisp.__main__:main"

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path    = "src/nya_lisp/_version.py"
pattern = '__version__(?:: str)? *= *\"(?P<version>[^\"]+)\"'

[dependency-groups]
dev = [ #
	"pre-commit>=4.6.2",
	"pytest==9.1.1",
	"ruff==0.16.9",
	"ty==0.0.84",
	"typing-extensions>=4.16.0",
	"uv==0.12.21",
]
